credentials:
  users:
    admin:
      password: 'presale'
      privileges:
        - permissions: [ read, write, execute ]
          spaces: [ key_value, users ]
groups:
  mygroup:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
                - uri: '127.0.0.1:3301'
app:
  file: 'init.lua'
