version: '3.7'

services:
  tarantool:
    image: tarantool/tarantool
    container_name: tarantool
    ports:
      - "3301:3301"
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
    command: tarantool /opt/tarantool/init.lua
    restart: unless-stopped
    networks:
      - vk

  api:
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      tarantool:
#        condition: service_healthy
#        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - vk
    depends_on:
      - tarantool


networks:
  vk:
    driver: bridge
