// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"VK-test/application/auth"
	"VK-test/application/reader"
	"VK-test/application/tokens"
	"VK-test/application/writer"
	"VK-test/handler/authhandler"
	"VK-test/handler/readhandler"
	"VK-test/handler/writehandler"
	"VK-test/infrastructure/http"
	"VK-test/infrastructure/logger"
	"VK-test/infrastructure/repo/kv_storage"
	"VK-test/infrastructure/repo/user_data"
	"VK-test/infrastructure/tarantool"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	payloadService := tokens.NewPayloadService()
	connection := tarantool.NewTarantoolClient()
	tarantoolUserRepo := user_data.NewTarantoolUserRepo(connection)
	service := auth.NewService(payloadService, tarantoolUserRepo)
	handler := authhandler.NewHandler(service)
	tarantoolDataRepo := kv_storage.NewTarantoolDataRepo(connection)
	writerService := writer.NewWriterService(tarantoolDataRepo)
	writehandlerHandler := writehandler.NewHandler(writerService)
	readerService := reader.NewReaderService(tarantoolDataRepo)
	readhandlerHandler := readhandler.NewHandler(readerService)
	handlerContainer := http.NewHandlerContainer(handler, writehandlerHandler, readhandlerHandler)
	zapLogger := logger.NewLogger()
	app := NewApp(handlerContainer, zapLogger)
	return app, nil
}

// wire.go:

// SuperSet is the Wire provider set that includes all the dependencies.
var SuperSet = wire.NewSet(kv_storage.NewTarantoolDataRepo, tokens.NewPayloadService, user_data.NewTarantoolUserRepo, auth.NewService, readhandler.NewHandler, authhandler.NewHandler, writehandler.NewHandler, reader.NewReaderService, writer.NewWriterService, http.NewHandlerContainer, logger.NewLogger, tarantool.NewTarantoolClient, NewApp, wire.Bind(new(writer.KeyValueRepo), new(*kv_storage.TarantoolDataRepo)), wire.Bind(new(auth.TokenService), new(*tokens.PayloadService)), wire.Bind(new(auth.UserRepo), new(*user_data.TarantoolUserRepo)), wire.Bind(new(readhandler.ReaderService), new(*reader.Service)), wire.Bind(new(writehandler.WriterService), new(*writer.Service)), wire.Bind(new(http.AuthHandler), new(*authhandler.Handler)), wire.Bind(new(http.ReadHandler), new(*readhandler.Handler)), wire.Bind(new(http.WriteHandler), new(*writehandler.Handler)), wire.Bind(new(authhandler.ServiceAuth), new(*auth.Service)), wire.Bind(new(reader.KeyValueRepo), new(*kv_storage.TarantoolDataRepo)))
